routes:
  /: home
  /fr/pricing/: plans
  /en/pricing/: plans-en
  /fr/coffeeshops/:
    controller: channel
    filter: tag:coffeeshop+tag:-hash-en
    template: index
  /en/coffeeshops/:
    controller: channel
    filter: tag:coffeeshop+tag:hash-en
    template: index-en

collections:
  /fr/:
    permalink: /fr/{slug}/
    template: index
    filter: "tag:-hash-en+tag:-hash-newsletter"
  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: "tag:hash-en+tag:-hash-newsletter"
  /fr/newsletters/:
    permalink: /fr/newsletters/{slug}/
    template: index
    filter: tag:hash-newsletter+tag:-hash-en
  /en/newsletters/:
    permalink: /fr/newsletters/{slug}/
    template: index-en
    filter: tag:hash-newsletter+tag:hash-en

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
