routes:
  /fr/:
    controller: channel
    template: index
    filter: "tag:-hash-en"

collections:
  /:
    permalink: /fr/{slug}/
    template: index
    filter: "tag:-hash-en"
  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: "tag:hash-en"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
